### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by DanielSporysz** [maciekkoz98/VirtualCameraWPF#1]
Hi Maciej,

I'd like to inform you that there is a spelling mistake in the README.md file. 

> This project simulates **ligth** reflections.

Meanwhile the spelling should be "light".

Sincerely,
Daniel

**Comment by maciekkoz98** [comment]
Thank you for letting me know about this issue. I will corrected this spelling mistake as soon as possible. 
Best wishes,
Maciej

**Comment by maciekkoz98** [comment]
Mistake was corrected. I'm closing the issue. Once more thank you for your commitment.
